### ISSUE TITLE
Incorrect handling of h5 file missing

### ISSUE THREAD

**Issue by cjordan** [MWATelescope/mwa_pb#2]
I would attempt to fix this myself, but I'm getting a headache looking at the code.  To reproduce:

- Install miniconda with the sh script online (https://docs.conda.io/en/latest/miniconda.html);
- Activate it;
- Install numpy, scipy and astropy;
- cd into a clone of mwa_pb, run `pip install .`
- Run Jack's srclist_by_beam and get:
```
$  /srclists/srclist_by_beam.py -n 100 --srclist=/srclists/srclist_pumav3_EoR0aegean_EoR1pietro+ForA.txt --metafits=1202937080.metafits --order=distance --no_patch --cutoff=30 --aocalibrate
# ERROR:mwa_pb.beam_full_EE: Cannot find beam model file /home/chj/miniconda2/lib/python2.7/site-packages/mwa_pb/data/mwa_full_embedded_element_pattern.h5
Traceback (most recent call last):
  File "/srclists/srclist_by_beam.py", line 476, in <module>
    beam_weights = get_beam_weights(ras=all_ras,decs=all_decs)
  File "/srclists/srclist_by_beam.py", line 428, in get_beam_weights
    XX,YY = primary_beam.MWA_Tile_full_EE([za], [az], freq=freqcent, delays=delays, zenithnorm=True, power=True, interp=False)
  File "/home/chj/miniconda2/lib/python2.7/site-packages/mwa_pb/primary_beam.py", line 89, in MWA_Tile_full_EE
    tile = beam_full_EE.get_AA_Cached(target_freq_Hz=freq)
  File "/home/chj/miniconda2/lib/python2.7/site-packages/mwa_pb/beam_full_EE.py", line 179, in get_AA_Cached
    a = ApertureArray(config.h5file, target_freq_Hz)
  File "/home/chj/miniconda2/lib/python2.7/site-packages/mwa_pb/beam_full_EE.py", line 117, in __init__
    pos = np.argmin(np.abs(freqs - target_freq_Hz))
TypeError: unsupported operand type(s) for -: 'list' and 'float'
```

Sprinkling some prints in `beam_full_EE.py` shows that `if h5filepath == config.h5file:` evaluates true, and that code then sets `freqs` to an empty list (and *not* a numpy array).  The next condition is `elif os.path.exists(h5filepath):`, and it seems to me that these conditions need to be somehow merged, as putting the h5 file in the expected location (`/home/chj/miniconda2/lib/python2.7/site-packages/mwa_pb/data/mwa_full_embedded_element_pattern.h5`) fixes the type error.

**Comment by andreww5au** [comment]
I've just pushed a change that gives an error if the file can't be found - it still sets freqs to an empty list and returns though, so it'll still fail later with the same TypeError. Not sure whether to call sys.exit(-1) if the h5 file isn't found, or to raise an AssertionError at the point where it looks for the file?

**Comment by cjordan** [comment]
I got the impression that if the h5 file isn't available, then some other beam was used?  If that's wrong, then this code should (IMO) throw an exception, otherwise it prints a warning and uses another beam.

**Comment by andreww5au** [comment]
I've just pushed a version that raises an IOError instead. There's no way that the primary_beam.MWA_Tile_full_EE() function can succeed if the h5 file doesn't exist. If that function throws an exception (because the h5 file with the full EE model can't be found) then it's up to Jack's code in /srclists/srclist_by_beam.py to call a different beam model function, like primary_beam.MWA_Tile_analytic().
