### ISSUE TITLE
Cerberus is down

### ISSUE THREAD

**Issue by NickSwainston** [MWATelescope/mwa_pb#8]
I'm not sure who to talk to about this but I can no longer use:
`wget http://cerberus.mwa128t.org/mwa_full_embedded_element_pattern.h5`
as the connection times out. Can anyone fix the server or know who can?

**Comment by andreww5au** [comment]
Cerberus is down because the power is out on site. Use this URL for the next few days instead:
wget http://orthrus.mwa128t.org/mwa_full_embedded_element_pattern.h5
